---
# tasks file for Buck

- name: Create Buck installation directory
  file: >
    path={{ buck_installation_dir }}
    state=directory
  tags: buck

- name: Clone Buck
  git: >
    repo={{ buck_repository_url }}
    dest={{ buck_installation_dir }}
    version={{ buck_revision }}
  tags: buck

- name: Build Buck
  command: >
    ant clean default
    chdir={{ buck_installation_dir }}
  tags: buck

- name: Create Buck bin directory
  file: >
    path={{ buck_bin_dir }}
    state=directory
  tags: buck

- name: Create buck symlink
  file: >
    src={{ buck_installation_dir }}/bin/buck
    dest={{ buck_bin_dir }}/buck
    state=link
  tags: buck

- name: Create buckd symlink
  file: >
    src={{ buck_installation_dir }}/bin/buckd
    dest={{ buck_bin_dir }}/buckd
    state=link
  tags: buck

